version: '3.4'

networks:
  itsds_v1:

services:
  sqlserver:
     image: mcr.microsoft.com/mssql/server:2019-latest
     ports:
        - 1433:1433
     environment:
        MSSQL_SA_PASSWORD: itsds@123
        ACCEPT_EULA: Y
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
        - sqlserver
    ports:
        - "5000:80"
    networks:
        - itsds_v1
  